services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
    command: yarn workspace frontend dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/.next
    env_file:
      - apps/frontend/.env
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    command: yarn workspace backend dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - apps/backend/.env
    ports:
      - "3001:3001"
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  app_network:
