[build]
builder = "dockerfile"
dockerfilePath = "apps/backend/Dockerfile"
dockerBuildTarget = "runner"

[deploy]
startCommand = "yarn workspace backend db:prepare && node /app/apps/backend/dist/index.js"
